@localHost=localhost:4004/odata/v4/main

GET http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

###

POST http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders(id=003c4b20-d11e-41e1-9d24-45acdbe301c2)
Content-Type: application/json

###

PUT http://localhost:4004/odata/v4/main/SalesOrderHeaders(id=f77271aa-97ef-4434-bcc9-e00dff2e19a9)
Content-Type: application/json

{
    "modifiedBy": "teste"
}
