@localHost=localhost:4004/odata/v4/main
@id=967a2735-47af-44cb-a4b0-3200af9cf711

GET http://localhost:4004/odata/v4/main/Customers
Content-Type: application/json

###
POST http://localhost:4004/odata/v4/main/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "Lucas",
    "lastName": "Cardoso",
    "email": "lucas.cardoso@moovi.com"
}


###
DELETE http://localhost:4004/odata/v4/main/Customers(id={{id}})
Content-Type: application/json

###

PUT http://localhost:4004/odata/v4/main/Customers(id={{id}})
Content-Type: application/json 

{
    "firstName": "John"
}